name = "CxxBulletPrintMWE"
uuid = "3b942826-76a3-11e9-350c-7dcfaa477486"
authors = ["Gustavo Goretkin <gustavo.goretkin@gmail.com>"]
version = "0.1.0"

[deps]
Bullet3 = "5e831d02-149c-5a5c-acc1-4ff8be61dc33"
Cxx = "a0b5b9ef-44b7-5148-a2d1-f6db19f3c3d2"
